using System.Globalization;
using System.Security.Cryptography;
using System.Text;

namespace Grimoire.EvalRunner.Workspace;

/// <summary>
/// T005 (026-guarded-tool-surface, SC-011): materializes the <c>lint-at-scale</c> eval
/// fixture — <c>lint-seeded-defects</c>' pages plus enough clean filler pages that reading
/// the whole wiki costs several times the scenario's declared context budget
/// (<c>LintScenarioDefinition.ContextBudgetTokens</c>, T006).
///
/// <para><b>Generated, never committed.</b> plan.md § Eval scope forbids authoring a corpus
/// into the repository; <c>backend/tests/Grimoire.AgentEvals/Fixtures/lint-at-scale/</c> is
/// git-ignored and rebuilt on demand. The generator is the artifact under review, not its
/// output.</para>
///
/// <para><b>Determinism is load-bearing.</b> The fixture tree feeds the recording staleness
/// fingerprint (<c>Fingerprints.Compute</c> hashes it file by file), so byte-identical
/// output across machines and runs is a correctness requirement, not a nicety: a generator
/// that varied would stale every recording it backs on every run. Hence a fixed word list
/// driven by a seeded LCG, fixed timestamps, invariant-culture formatting, LF line endings,
/// and ordinal sorting — no <see cref="Random"/>, no <c>DateTime.Now</c>, no culture- or
/// filesystem-order dependence.</para>
///
/// <para><b>The filler is deliberately clean.</b> Every generated page carries two
/// taxonomy-conforming tags, a <c>high</c> confidence score with a reason, an accurate
/// <c>inbound_links</c> count, and an index entry — so it presents none of the defect
/// categories the Lint agent looks for, and no seeded defect is crowded out of the report
/// by generated noise. <c>high</c> confidence also keeps filler out of the Review Window
/// check, which considers only <c>low</c>-confidence pages: a fixed <c>last_reviewed</c>
/// date on a low-confidence page would age into a review candidate as the calendar moved,
/// making the fixture's defect set a function of the date it was surveyed.</para>
/// </summary>
public static class LintAtScaleFixture
{
    public const string FixtureName = "lint-at-scale";

    /// <summary>Source fixture whose seeded defects this one preserves verbatim.</summary>
    public const string SourceFixtureName = "lint-seeded-defects";

    /// <summary>
    /// Filler page count. Chosen with <see cref="ParagraphsPerPage"/> so the generated wiki
    /// is roughly 3–4x <c>LintAtScaleSurvey</c>'s context budget: reading everything is
    /// decisively over the guard, while the fixture stays small enough to generate and copy
    /// per sample in well under a second.
    /// </summary>
    public const int FillerPageCount = 60;

    private const int ParagraphsPerPage = 6;
    private const int SentencesPerParagraph = 5;
    private const string FillerFolder = "reference";

    /// <summary>Bumped whenever the generated bytes would change, so a stale tree is rebuilt.</summary>
    private const int GeneratorVersion = 2;

    /// <summary>
    /// Serializes generation across the process. Every consumer reaches the generated
    /// fixture through <c>EvalPaths.FixtureWikiRoot</c>, which calls <see cref="Ensure"/>,
    /// and xUnit runs test classes in parallel collections — so without this two callers
    /// can enter the rebuild path at once, one deleting the tree recursively while the
    /// other writes into it (<c>IOException: Directory not empty</c>) or hashes it
    /// half-built. The lock is what actually makes the "no caller can observe a half-built
    /// tree" guarantee documented on <c>FixtureWikiRoot</c> true.
    /// </summary>
    private static readonly Lock GenerationGate = new();

    /// <summary>
    /// Materializes the fixture if it is absent or was produced by different generator
    /// inputs. Idempotent and cheap on the common path: a stamp file records the hash of
    /// the generator's version, parameters and source tree, and a matching stamp short-
    /// circuits before any file is written.
    /// </summary>
    public static void Ensure(string fixturesRoot)
    {
        lock (GenerationGate)
        {
            EnsureCore(fixturesRoot);
        }
    }

    private static void EnsureCore(string fixturesRoot)
    {
        var wikiRoot = Path.Combine(fixturesRoot, FixtureName, "wiki");
        var sourceWiki = Path.Combine(fixturesRoot, SourceFixtureName, "wiki");
        if (!Directory.Exists(sourceWiki))
        {
            throw new InvalidOperationException(
                $"Cannot generate '{FixtureName}': source fixture '{SourceFixtureName}' not found at {sourceWiki}.");
        }

        var stampPath = Path.Combine(fixturesRoot, FixtureName, ".generator-stamp");
        var stamp = ComputeStamp(sourceWiki);
        if (File.Exists(stampPath)
            && string.Equals(File.ReadAllText(stampPath), stamp, StringComparison.Ordinal)
            && Directory.Exists(wikiRoot))
        {
            return;
        }

        if (Directory.Exists(wikiRoot))
        {
            Directory.Delete(wikiRoot, recursive: true);
        }

        Directory.CreateDirectory(wikiRoot);
        Directory.CreateDirectory(Path.Combine(wikiRoot, FillerFolder));

        foreach (var source in Directory.EnumerateFiles(sourceWiki, "*", SearchOption.AllDirectories)
                     .OrderBy(p => p, StringComparer.Ordinal))
        {
            var relative = Path.GetRelativePath(sourceWiki, source);
            var target = Path.Combine(wikiRoot, relative);
            Directory.CreateDirectory(Path.GetDirectoryName(target)!);
            File.Copy(source, target, overwrite: true);
        }

        var slugs = Enumerable.Range(1, FillerPageCount).Select(SlugFor).ToArray();
        for (var i = 0; i < slugs.Length; i++)
        {
            // Each filler page links to its successor (wrapping), so every filler page has
            // exactly one inbound link from a page plus one from index.md — a count the
            // page records accurately, presenting no inbound-link defect.
            var successor = slugs[(i + 1) % slugs.Length];
            var path = Path.Combine(wikiRoot, FillerFolder, slugs[i] + ".md");
            WriteAllTextLf(path, RenderFillerPage(i + 1, slugs[i], successor));
        }

        var indexPath = Path.Combine(wikiRoot, "index.md");
        WriteAllTextLf(indexPath, File.ReadAllText(indexPath).TrimEnd('\n') + "\n" + RenderIndexSection(slugs));

        Directory.CreateDirectory(Path.GetDirectoryName(stampPath)!);
        WriteAllTextLf(stampPath, stamp);
    }

    private static string SlugFor(int ordinal)
        => "reference-topic-" + ordinal.ToString("000", CultureInfo.InvariantCulture);

    private static string RenderIndexSection(IReadOnlyList<string> slugs)
    {
        var builder = new StringBuilder();
        builder.Append("\n## Reference\n\n");
        builder.Append(
            "Generated reference material (T005, 026-guarded-tool-surface): clean pages carrying no\n"
            + "seeded defect, present so that reading the whole wiki costs several times this\n"
            + "scenario's context budget.\n\n");
        for (var i = 0; i < slugs.Count; i++)
        {
            builder.Append("- [[").Append(slugs[i]).Append("]] — ").Append(DescriptionFor(i + 1)).Append('\n');
        }

        return builder.ToString();
    }

    private static string DescriptionFor(int ordinal)
    {
        var rng = new Lcg((ulong)ordinal * 6364136223846793005UL + 1442695040888963407UL);
        return Fill(DescriptionTemplates[(int)(rng.Next() % (ulong)DescriptionTemplates.Length)], ref rng);
    }

    private static string RenderFillerPage(int ordinal, string slug, string successorSlug)
    {
        var rng = new Lcg((ulong)ordinal * 2862933555777941757UL + 3037000493UL);
        var title = Capitalize(Words(ref rng, 3));
        var builder = new StringBuilder();

        builder.Append("---\n");
        builder.Append("type: Concept\n");
        builder.Append("title: ").Append(title).Append('\n');
        builder.Append("description: ").Append(DescriptionFor(ordinal)).Append('\n');
        // Fixed timestamp: the fixture's content must not depend on when it was generated.
        builder.Append("timestamp: 2026-05-01T00:00:00Z\n");
        builder.Append("tags:\n");
        builder.Append("  - concept/Reference\n");
        builder.Append("  - pattern/").Append(Capitalize(Word(ref rng))).Append('\n');
        builder.Append("confidence: high\n");
        builder.Append("confidence_reason: \"Generated reference page; internally consistent.\"\n");
        builder.Append("inbound_links: 2\n");
        builder.Append("---\n\n");
        builder.Append("# ").Append(title).Append("\n\n");

        for (var p = 0; p < ParagraphsPerPage; p++)
        {
            for (var s = 0; s < SentencesPerParagraph; s++)
            {
                builder.Append(Fill(SentenceTemplates[(int)(rng.Next() % (ulong)SentenceTemplates.Length)], ref rng));
                builder.Append(s == SentencesPerParagraph - 1 ? "\n" : " ");
            }

            builder.Append('\n');
        }

        builder.Append("See also [[").Append(successorSlug).Append("]] for the adjacent treatment of this material.\n");
        return builder.ToString();
    }

    // ── Deterministic text generation ────────────────────────────────────────────

    private static readonly string[] Vocabulary =
    [
        "boundary", "invariant", "throughput", "latency", "checkpoint", "partition", "quorum",
        "idempotent", "replica", "coordinator", "lease", "backpressure", "scheduler", "envelope",
        "projection", "snapshot", "reconciliation", "handshake", "watermark", "compaction",
        "tombstone", "gossip", "arbiter", "sequencer", "batch", "window", "digest", "manifest",
        "ledger", "epoch", "fence", "shard", "cursor", "queue", "retry", "budget", "quota",
        "signal", "probe", "sampler", "exporter", "collector", "span", "trace", "counter",
        "histogram", "threshold", "guardrail", "policy", "adapter", "port", "registry",
    ];

    private static string Word(ref Lcg rng) => Vocabulary[(int)(rng.Next() % (ulong)Vocabulary.Length)];

    private static string Words(ref Lcg rng, int count)
    {
        var builder = new StringBuilder();
        for (var i = 0; i < count; i++)
        {
            if (i > 0)
            {
                builder.Append(' ');
            }

            builder.Append(Word(ref rng));
        }

        return builder.ToString();
    }

    /// <summary>
    /// Sentence frames with <c>{0}</c>-style slots filled from <see cref="Vocabulary"/>.
    /// Templates rather than free word salad: an agent surveying sixty pages of
    /// grammatically random nouns would quite reasonably report them as a content-quality
    /// defect, which would crowd the seeded defects out of the Findings Report and fail the
    /// scenario for a reason that has nothing to do with SC-011. The filler has to read as
    /// ordinary, unremarkable reference prose — material worth navigating past, not material
    /// worth reporting.
    /// </summary>
    private static readonly string[] SentenceTemplates =
    [
        "The {0} bounds how often the {1} is refreshed.",
        "A {0} that outlives its {1} is discarded before the next {2} runs.",
        "Each {0} carries the {1} that produced it, so a later {2} can be attributed to its origin.",
        "When the {0} falls behind, the {1} applies backpressure instead of dropping work.",
        "The {0} advances only after the {1} has been durably recorded.",
        "Two replicas may disagree about the {0} until the {1} converges; the {2} settles the difference.",
        "Reads observe the {0} as of the last {1}, never a partially applied {2}.",
        "The {0} is sized from the {1} rather than the {2}, so it degrades predictably under load.",
        "A failed {0} is retried at most once per {1}; beyond that the {2} is surfaced to the caller.",
        "Operators tune the {0} through the {1}; the {2} is derived from it and never set directly.",
        "The {0} and the {1} are updated together, so an observer never sees one without the other.",
        "Holding the {0} across a {1} is what makes the {2} safe to repeat.",
    ];

    private static readonly string[] DescriptionTemplates =
    [
        "How the {0} bounds the {1} under sustained load.",
        "Why the {0} is derived from the {1} rather than configured directly.",
        "The relationship between the {0}, the {1}, and the {2}.",
        "When to prefer a {0} over a {1} for coordinating work.",
        "What the {0} guarantees once the {1} has been recorded.",
    ];

    /// <summary>Fills a template's <c>{n}</c> slots with vocabulary words drawn from <paramref name="rng"/>.</summary>
    private static string Fill(string template, ref Lcg rng)
    {
        var result = template;
        for (var slot = 0; slot < 3; slot++)
        {
            var token = "{" + slot.ToString(CultureInfo.InvariantCulture) + "}";
            if (result.Contains(token, StringComparison.Ordinal))
            {
                result = result.Replace(token, Word(ref rng), StringComparison.Ordinal);
            }
        }

        return result;
    }

    private static string Capitalize(string value)
        => value.Length == 0 ? value : char.ToUpperInvariant(value[0]) + value[1..];

    /// <summary>
    /// A 64-bit linear congruential generator. Deliberately hand-rolled rather than
    /// <see cref="Random"/>: the .NET shared implementation gives no cross-version stability
    /// guarantee for a given seed, and this fixture's bytes must not move under a runtime
    /// upgrade (see the determinism note on the class).
    /// </summary>
    private struct Lcg(ulong seed)
    {
        private ulong _state = seed | 1UL;

        public ulong Next()
        {
            _state = unchecked((_state * 6364136223846793005UL) + 1442695040888963407UL);
            return _state >> 17;
        }
    }

    private static void WriteAllTextLf(string path, string content)
        => File.WriteAllText(path, content.Replace("\r\n", "\n", StringComparison.Ordinal), new UTF8Encoding(false));

    private static string ComputeStamp(string sourceWiki)
    {
        var builder = new StringBuilder();
        builder.Append("v").Append(GeneratorVersion)
            .Append(";pages=").Append(FillerPageCount)
            .Append(";paras=").Append(ParagraphsPerPage)
            .Append(";sentences=").Append(SentencesPerParagraph)
            .Append(";source=");
        foreach (var file in Directory.EnumerateFiles(sourceWiki, "*", SearchOption.AllDirectories)
                     .OrderBy(p => p, StringComparer.Ordinal))
        {
            builder.Append(Path.GetRelativePath(sourceWiki, file).Replace('\\', '/'))
                .Append(':')
                .Append(Convert.ToHexStringLower(SHA256.HashData(File.ReadAllBytes(file))))
                .Append(';');
        }

        return Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(builder.ToString())));
    }
}
