litellm_settings:
  drop_params: true

model_list:
  - model_name: nvidia-model
    litellm_params:
      model: nvidia_nim/minimaxai/minimax-m3
      api_key: os.environ/NVIDIA_NIM_API_KEY
      #api_base: https://integrate.api.nvidia.com/v1
